# Generated by Django 4.0 on 2023-01-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
