# Generated by Django 4.0.6 on 2022-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_expense_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
