# Generated by Django 4.1.2 on 2022-10-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_expense_date_created_alter_expense_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="no image", upload_to="images/"),
        ),
    ]
