# Generated by Django 4.1.2 on 2022-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
