# Generated by Django 4.1.3 on 2022-12-30 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_todouser_todo_todo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="todo_user",
        ),
        migrations.AddField(
            model_name="todouser",
            name="todo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.todo"
            ),
        ),
    ]
