# Generated by Django 4.1.3 on 2023-01-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_todouser_todo_todo_todo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
